version: "3.3"
# Указываем раздел со связанными сервисами
services:
  # Первый сервис, nginx
  nginx:
    image: nginx:latest
    # Пробрасываем порты 80 для http и 443 для https
    ports:
      - "89:80"
      - "449:443"
    # Опциональный параметр с именем контейнера
    container_name: proxy_nginx
    volumes:
      # Используем свой nginx конфиг, он заменит дефолтный в контейнере
      - ./nginx:/etc/nginx/conf.d
      # Монтируем папку с логами на хост машину для более удобного доступа
      - ./logs:/var/log/nginx/
      #  Монтируем папку со статикой
      - ./static:/var/www/static
  # Второй сервис Nuxt.js приложение
  nuxt:
    container_name: nuxt_app
    # Также пробрасываем порт на котором висит приложение
    ports:
      - "3000:3000"
    build: .
    secrets:
      - mongo-uri
      - jwt

secrets:
  mongo-uri:
    file: ./.secrets/mongo-uri
  jwt:
    file: ./.secrets/jwt
  