version: "3.3"
# Указываем раздел со связанными сервисами
services:
  # Первый сервис, nginx
  nginx:
    image: nginx:latest
    restart: unless-stopped
    # Пробрасываем порты 80 для http и 443 для https
    ports:
      - "89:80"
      - "449:443"
    # Опциональный параметр с именем контейнера
    container_name: wegeograph_proxy
    volumes:
      # Используем свой nginx конфиг, он заменит дефолтный в контейнере
      - ./nginx:/etc/nginx/conf.d
      # Монтируем папку с логами на хост машину для более удобного доступа
      - ./logs:/var/log/nginx/
      #  Монтируем папку со статикой
      - ./static:/var/www/static
  # Второй сервис Nuxt.js приложение
  nuxt:
    container_name: wegeograph
    restart: unless-stopped
    # Также пробрасываем порт на котором висит приложение
    ports:
      - "5353:5353"
    build: .
  